# .github/workflows/publish.yml
name: Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker image build -f Containerfile --tag ghcr.io/containerpak/chrome:main .

      - name: Push to GHCR
        run: |
          echo "${{ env.REGISTRY_PASSWORD }}" | docker login ghcr.io -u "${{ env.REGISTRY_USER }}" --password-stdin
          docker image push ghcr.io/containerpak/chrome:main
